# Generated by Django 2.1.4 on 2018-12-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwevent',
            name='gw_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
