# Generated by Django 2.1.4 on 2019-02-12 20:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='bkick',
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='bhsigmafrac',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='natal_kick',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], size=None),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='polar_kick_angle',
            field=models.FloatField(default=90.0),
        ),
    ]
