# Generated by Django 2.1.4 on 2019-01-03 20:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0002_auto_20190103_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='convergence_params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['mass_1', 'mass_2', 'porb', 'ecc'], size=None),
        ),
    ]
