# Generated by Django 2.1.4 on 2019-01-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0003_auto_20190103_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='convergence_params',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='final_kstar1',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='final_kstar2',
        ),
    ]
