# Generated by Django 2.1.4 on 2019-02-12 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0004_auto_20190212_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='final_kstar1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[13, 14], size=None),
        ),
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='final_kstar2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[13, 14], size=None),
        ),
    ]
