# Generated by Django 2.1.4 on 2019-01-03 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0004_auto_20190103_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='merger_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), default=['-001'], size=None),
        ),
    ]
