# Generated by Django 2.1.4 on 2019-02-12 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0005_auto_20190212_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='merger_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=['-001', '1313', '1314', '1413', '1414'], size=None),
        ),
    ]
