# Generated by Django 2.1.4 on 2019-01-03 20:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0005_auto_20190103_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='galaxy_component',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='initial_samp',
        ),
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='merger_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=['-001'], size=None),
        ),
    ]
