# Generated by Django 2.1.4 on 2019-03-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0006_auto_20190212_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='aic',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='cehestarflag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='cekickflag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='cemergeflag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='ecsn_mlow',
            field=models.IntegerField(default=1.6),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='ecsnp',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='sigmadiv',
            field=models.FloatField(default=-20.0),
        ),
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='pts1',
            field=models.FloatField(default=0.001),
        ),
    ]
