# Generated by Django 2.1.4 on 2019-01-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0006_auto_20190103_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='Niter',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='Nstep',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='metallicity',
        ),
    ]
