# Generated by Django 2.1.4 on 2019-01-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0007_auto_20190103_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='Niter',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='Nstep',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='metallicity',
            field=models.FloatField(default=0.002),
        ),
    ]
