# Generated by Django 2.1.4 on 2019-03-26 22:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0007_auto_20190326_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpopsynthmodel',
            old_name='natal_kick',
            new_name='natal_kick_array',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='b_0',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='bacc',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='epoch',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='massc',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='opsin',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='tacc',
        ),
        migrations.RemoveField(
            model_name='newpopsynthmodel',
            name='tphys',
        ),
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='qcrit_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], size=None),
        ),
    ]
