# Generated by Django 2.1.4 on 2019-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0008_auto_20190326_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='galaxy_component',
            field=models.CharField(choices=[('ThinDisk', 'ThinDisk'), ('Bulge', 'Bulge'), ('ThickDisk', 'ThickDisk'), ('DeltaBurst', 'DeltaBurst')], max_length=20),
        ),
    ]
