# Generated by Django 2.1.4 on 2019-01-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0008_auto_20190103_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='galaxy_component',
            field=models.CharField(choices=[('THINDISK', 'ThinDisk'), ('BULGE', 'Bulge'), ('THICKDISK', 'ThickDisk'), ('DELTABURST', 'DeltaBurst'), ('FIRE', 'FIRE')], default='ThinDisk', max_length=20),
            preserve_default=False,
        ),
    ]
