# Generated by Django 2.1.4 on 2019-04-03 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0010_auto_20190326_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='natal_kick_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[-100.0, -100.0, -100.0, -100.0, -100.0, -100.0], size=None),
        ),
    ]
