# Generated by Django 2.1.4 on 2019-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0012_remove_newpopsynthmodel_merger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpopsynthmodel',
            name='lisa_sources',
            field=models.BooleanField(default=False),
        ),
    ]
