# Generated by Django 2.1.4 on 2019-04-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0013_newpopsynthmodel_lisa_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='bhflag',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='ecsn_mlow',
            field=models.FloatField(default=1.4),
        ),
    ]
