# Generated by Django 2.1.4 on 2019-04-25 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsynth_generation', '0014_auto_20190404_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='bhflag',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='newpopsynthmodel',
            name='binary_state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 1], size=None),
        ),
    ]
